import './global.css';
import { AppLayout } from '@clear-budget/shared/ui';
import SettingsIcon from '@mui/icons-material/Settings';
import ShieldIcon from '@mui/icons-material/Security';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};


export const adminMenu = [
  {
    label: 'Gestión',
    icon: <SettingsIcon />,
    children: [
      { label: 'Usuarios', route: '/usuarios' },
      { label: 'Roles', route: '/roles' },
      { label: 'Permisos', route: '/permisos' }
    ]
  },
  {
    label: 'Auditoría',
    icon: <ShieldIcon />,
    children: [
      { label: 'Logs', route: '/auditoria/logs' }
    ]
  }
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body>
        <AppLayout title='Clear Budget' menuItems={adminMenu}>{children}</AppLayout>
      </body>
    </html>
  );
}
