import './global.css';
import { AppLayout } from '@clear-budget/shared/ui';
import SettingsIcon from '@mui/icons-material/Settings';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};


export const adminMenu = [
  {
    label: 'Management',
    icon: <SettingsIcon />,
    children: [
      { label: 'Categories', route: '/categories' },
    ]
  },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppLayout title='Clear Budget' menuItems={adminMenu}>{children}</AppLayout>
      </body>
    </html>
  );
}
