import './global.css';
import ClientAppLayout from './ClientAppLayout';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientAppLayout>{children}</ClientAppLayout>
      </body>
    </html>
  );
}

